import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className}>
        <div className="navbar ">
          <div className="flex-1">
            <a className="btn btn-ghost normal-case text-xl">Next.js Playground</a>
          </div>
          <div className="flex-none">
            <ul className="menu menu-horizontal px-1">
              <li><Link href="/" className="link link-hover">Home</Link></li>
              <li><Link href="/users" className="link link-hover">Users</Link></li>
            </ul>
          </div>
        </div>

        <div className="flex justify-center p-8">
          <div className="w-full max-w-4xl bg-white rounded-lg shadow-md p-8">
              {children}
          </div>
        </div>
      </body>
    </html>
  )
}
